# Generated by Django 4.1.7 on 2023-03-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_otprecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="otprecord",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
