# Generated by Django 4.1.7 on 2023-03-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("web_code", models.CharField(max_length=128)),
                (
                    "country_code",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "flag",
                    models.ImageField(
                        blank=True, null=True, upload_to="countries/flags/"
                    ),
                ),
                ("phone_code", models.CharField(blank=True, max_length=128, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "phone_number_length",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "country",
                "verbose_name_plural": "countries",
                "db_table": "main_country",
                "ordering": ("name",),
            },
        ),
    ]
